server:
  port: 8081
  
eureka:
  server:
    #eviction-interval-timer-in-ms: 1000
    enableSelfPreservation: true
  client:
    registerWithEureka: false #telling the server not to register himself
    fetchRegistry: false